export enum DrumsEnum {
  Cameo = 'CAMEO_SN.WAV',
  Crash1 = 'CRASH1.WAV',
  Crash2 = 'CRASH2.WAV',
  GateKick = 'GATEKICK.WAV',
  Kick = 'KICK.WAV',
  Kick1 = 'KICK1.WAV',
  Ride = 'RIDE.WAV',
  Rim = 'RIM.WAV',
  Snare = 'SN1.WAV',
  Snare2 = 'SN2.WAV',
  Tom1F = 'TOM1F.WAV',
  Tom1L = 'TOM1L.WAV',
  Tom1M = 'TOM1M.WAV',
  Tom2F = 'TOM2FAMBI.WAV',
  Tom2L = 'TOM2LAMBI.WAV',
  Tom2M = 'TOM2MAMBI.WAV',
}
